# Generated by Django 3.0.5 on 2020-05-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, verbose_name='이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='가입시간')),
            ],
            options={
                'verbose_name': 'aboutfit user',
                'verbose_name_plural': 'aboutfit user group',
                'db_table': 'aboutfit_user',
            },
        ),
    ]
