# Generated by Django 3.1 on 2020-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200827_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Femail'), ('N', 'Not to disclose')], default='N', max_length=10),
        ),
    ]
