# Generated by Django 3.0.5 on 2020-05-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0002_auto_20200502_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': '새커뮤니티 사용자', 'verbose_name_plural': '새커뮤니티 사용자'},
        ),
        migrations.AddField(
            model_name='newuser',
            name='useremail',
            field=models.EmailField(default='default@email.com', max_length=64, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
