# Generated by Django 3.0.5 on 2020-05-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0003_auto_20200504_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': '새 커뮤니티 사용자', 'verbose_name_plural': '새 커뮤니티 사용자 모음'},
        ),
    ]
