# Generated by Django 3.1 on 2020-08-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default=('user', 'user'), max_length=8, verbose_name='회원등급'),
        ),
    ]
