# Generated by Django 3.0.3 on 2020-02-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문내용')),
                ('category', models.CharField(choices=[('DV', 'Development'), ('PS', 'Personal'), ('AF', 'Africa')], default=('DV', 'Development'), max_length=3, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=50, verbose_name='해쉬태그')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='댓글작성자')),
                ('content', models.CharField(max_length=200, verbose_name='댓글내용')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Article')),
            ],
        ),
    ]
