# Generated by Django 3.1 on 2020-09-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('content', 'order')},
        ),
    ]
