# Generated by Django 3.1 on 2020-09-07 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0004_followreleation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followreleation',
            name='follower',
        ),
        migrations.AddField(
            model_name='followreleation',
            name='follower',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='auth.user'),
            preserve_default=False,
        ),
    ]
