# Generated by Django 3.1 on 2020-09-08 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0005_auto_20200907_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followreleation',
            name='followee',
        ),
        migrations.AddField(
            model_name='followreleation',
            name='followee',
            field=models.ManyToManyField(related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followreleation',
            name='follower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
