# Generated by Django 3.0.5 on 2020-05-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='주문날짜')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='고객')),
            ],
            options={
                'verbose_name': 'aboutfit order',
                'verbose_name_plural': 'aboutfit order group',
                'db_table': 'aboutfit_order',
            },
        ),
    ]
