# Generated by Django 3.0.5 on 2020-05-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_user', '0003_auto_20200504_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('conetent', models.TextField(verbose_name='내용')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_user.NewUser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '뉴 커뮤니티 게시글',
                'verbose_name_plural': '뉴 커뮤니티 게시글 모음',
                'db_table': 'new_community_board',
            },
        ),
    ]
