# Generated by Django 3.0.5 on 2020-05-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newboard',
            old_name='conetent',
            new_name='content',
        ),
    ]
