# Generated by Django 3.0.5 on 2020-05-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='상품명')),
                ('price', models.IntegerField(max_length=32, verbose_name='상품가격')),
                ('stuck', models.IntegerField(max_length=32, verbose_name='상품재고')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': 'aboutfit product',
                'verbose_name_plural': 'aboutfit product group',
                'db_table': 'aboutfit_product',
            },
        ),
    ]
