# Generated by Django 3.0.5 on 2020-05-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='상품가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stuck',
            field=models.IntegerField(verbose_name='상품재고'),
        ),
    ]
