# Generated by Django 3.1 on 2020-08-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcMallOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='주문수량')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='주문시간')),
                ('fcuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.fcuser', verbose_name='주문자명')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.fcmallproduct', verbose_name='주문상품')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'db_table': 'fcmall_order',
            },
        ),
    ]
